project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://tiffany-ngli.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - text: "MP#01"
        href: "./mp01.html"
      - text: "MP#02"
        href: "./mp02.html"
      - text: "MP#03"
        href: "./mp03.html"
format:
  html:
    theme: morph
    toc: false

editor:
  mode: source